# matutils pre-built mutation-annotated tree from
# http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/
mat_tree: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/11/07/public-2022-11-07.all.masked.nextclade.pangolin.pb.gz

# Reference GTF and FASTA, and location of spike coding sequence
ref_fasta: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz
ref_gtf: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/genes/ncbiGenes.gtf.gz

# Only keep nextstrain clades with at least this many samples in mutation-annotated tree
min_clade_samples: 10000

# Subset samples based on whether they start with these regex matches
sample_subsets:
  all: .  # regex to match anything
  USA: USA
  England: England

# Founder genotypes for nextstrain clades from Richard Neher
clade_founder_json: https://raw.githubusercontent.com/neherlab/SC2_variant_rates/cd6e016a511098123b6ce9ed874f58a7b789b34c/data/clade_gts.json

# For counting mutations, exclude any branches with more than this many nucleotide
# mutations or more than this many reversions to reference or clade founder
max_nt_mutations: 4
max_reversions_to_ref: 1
max_reversions_to_clade_founder: 1

# Exclude nucleotide mutations from reference to clade founder and their reversions.
# These sites have higher than normal errors due to calling of missing bases to reference.
exclude_ref_to_founder_muts: true

# sites to exclude the following sites (set to null for no exclusions)
sites_to_exclude:
  # Sites in Table S1 of https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009175
  - 153
  - 1149
  - 2198
  - 3145
  - 3564
  - 3778
  - 4050
  - 6255
  - 8022
  - 8790
  - 13402
  - 13947
  - 22802
  - 24389
  - 24390
  - 24933
  # sites specified for exclusion because they have extremely high mutation
  # frequency in some clade
  - 5629  # T5629G is much higher (~5% of all) in clade 20A than any other mutation.
  - 6851  # C6851A and its reversion are top two mutations in 20C at ~5% and ~3% of all mutations
  - 7328  # ~6% of all mutations in clade 21I, also highly mutated (~4% of all) in several other clades
  - 28095  # ~11% of all mutations in clade 20I
  - 29362  # ~30% of all mutations in clade 21C

# for analysis of 4-fold synonymous mutation spectra/rates, only keep clade subsets with
# at least this many non-excluded mutation counts
synonymous_spectra_min_counts: 5000

# Define common names of Nexstrain clades
clade_synonyms:
  20A: B.1
  20B: B.1.1
  20C: B.1.367
  20E: B.1.177
  20G: B.1.2
  20I: Alpha
  21C: Epsilon
  21I: Delta
  21J: Delta
  21K: Omicron BA.1
  21L: Omicron BA.2
  22A: Omicron BA.4
  22B: Omicron BA.5
  22C: Omicron BA.2.12.1

# Orf1ab to Nsp numbering (nucleotide start in Orf1ab) from
# https://github.com/theosanderson/Codon2Nucleotide/blob/main/src/App.js
orf1ab_to_nsps:
  nsp1: 1
  nsp2: 181
  nsp3: 819
  nsp4: 2764
  nsp5: 3264
  nsp6: 3570
  nsp7: 3860
  nsp8: 3943
  nsp9: 4141
  nsp10: 4254
  nsp12: 4393
  nsp13: 5325
  nsp14: 5926
  nsp15: 6453
  nsp16: 6799
