name: ete3
channels:
  - etetoolkit
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - ete3=3.1.2
  - jupyterlab
  - matplotlib=3
  - papermill
  - pandas=1.4
  - python=3.9
  - pyyaml
  - snakemake
