name: R
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - r-essentials
  - r-base
  - r-broom
  - r-cowplot
  - r-dplyr
  - r-ggplot2
  - r-scales
  - r-tidyverse
  - r-vegan
